package com.weein.bigdata.dao;
import com.weein.common.base.dao.IBaseMapper;
import com.weein.bigdata.base.entity.BigdataUserOfGroupDO;

/**
 *com.weein.bigdata.dao.IBigdataUserOfGroupMapper.java
 *2018-09-30 01:08:56
 * This was class generated by ant velocity
 */
public interface IBigdataUserOfGroupMapper extends IBaseMapper<BigdataUserOfGroupDO,java.lang.String> {
 
}


