package com.weein.bigdata.dao;
import com.weein.common.base.dao.IBaseMapper;
import com.weein.bigdata.base.entity.BigdataGroupInfoDO;

/**
 *com.weein.bigdata.dao.IBigdataGroupInfoMapper.java
 *2018-09-30 12:57:22
 * This was class generated by ant velocity
 */
public interface IBigdataGroupInfoMapper extends IBaseMapper<BigdataGroupInfoDO,java.lang.String> {
 
}


