package com.weein.bigdata.dao;
import com.weein.common.base.dao.IBaseMapper;
import com.weein.bigdata.base.entity.BigdataGroupProductConfigurationDO;

/**
 *com.weein.bigdata.dao.IBigdataGroupProductConfigurationMapper.java
 *2018-09-30 12:58:42
 * This was class generated by ant velocity
 */
public interface IBigdataGroupProductConfigurationMapper extends IBaseMapper<BigdataGroupProductConfigurationDO,java.lang.String> {
	int deleteByGroupId(String groupId);
}


