package com.weein.bigdata.dao;
import com.weein.common.base.dao.IBaseMapper;
import com.weein.bigdata.base.entity.CouponInfoDO;

/**
 *com.weein.bigdata.dao.ICouponInfoMapper.java
 *2018-08-29 01:27:31
 * This was class generated by ant velocity
 */
public interface ICouponInfoMapper extends IBaseMapper<CouponInfoDO,java.lang.String> {
 
}


