package com.weein.bigdata.dao;
import com.weein.common.base.dao.IBaseMapper;
import com.weein.bigdata.base.entity.MobikeCityDO;

/**
 *com.weein.bigdata.dao.IMobikeCityMapper.java
 *2018-09-27 05:18:25
 * This was class generated by ant velocity
 */
public interface IMobikeCityMapper extends IBaseMapper<MobikeCityDO,java.lang.Integer> {
 
}


