package com.weein.bigdata.dao;
import com.weein.common.base.dao.IBaseMapper;
import com.weein.bigdata.base.entity.ProductInfoDO;

/**
 *com.weein.bigdata.dao.IProductInfoMapper.java
 *2018-09-29 03:22:57
 * This was class generated by ant velocity
 */
public interface IProductInfoMapper extends IBaseMapper<ProductInfoDO,java.lang.String> {
 
}


