package com.weein.bigdata.core.service;
import com.weein.bigdata.core.service.IBaseService;
import com.weein.bigdata.base.entity.BigdataGroupProductConfigurationDO;
/**
 *com.weein.bigdata.core.service.IBigdataGroupProductConfigurationServices.java
 *2018-09-30 12:58:42
 * This was class generated by ant velocity
 */
public interface IBigdataGroupProductConfigurationService extends IBaseService<BigdataGroupProductConfigurationDO,java.lang.String>{
	 int deleteByGroupId(String groupId);
}
