package com.weein.bigdata.core.service;
import com.weein.bigdata.core.service.IBaseService;
import com.weein.bigdata.base.entity.BigdataUserOfGroupDO;
/**
 *com.weein.bigdata.core.service.IBigdataUserOfGroupServices.java
 *2018-09-30 01:08:56
 * This was class generated by ant velocity
 */
public interface IBigdataUserOfGroupService extends IBaseService<BigdataUserOfGroupDO,java.lang.String>{

}
