package com.weein.bigdata.core.service;
import com.weein.bigdata.core.service.IBaseService;
import com.weein.bigdata.base.entity.BigdataGroupInfoDO;
/**
 *com.weein.bigdata.core.service.IBigdataGroupInfoServices.java
 *2018-09-30 12:57:22
 * This was class generated by ant velocity
 */
public interface IBigdataGroupInfoService extends IBaseService<BigdataGroupInfoDO,java.lang.String>{

}
