package com.weein.bigdata.core.service;
import com.weein.bigdata.core.service.IBaseService;
import com.weein.bigdata.base.entity.CouponInfoDO;
/**
 *com.weein.bigdata.core.service.ICouponInfoServices.java
 *2018-08-29 01:27:31
 * This was class generated by ant velocity
 */
public interface ICouponInfoService extends IBaseService<CouponInfoDO,java.lang.String>{

}
