package com.weein.bigdata.core.service;
import com.weein.bigdata.core.service.IBaseService;
import com.weein.bigdata.base.entity.MobikeCityDO;
/**
 *com.weein.bigdata.core.service.IMobikeCityServices.java
 *2018-09-27 05:18:25
 * This was class generated by ant velocity
 */
public interface IMobikeCityService extends IBaseService<MobikeCityDO,java.lang.Integer>{

}
