package com.weein.bigdata.core.service;
import com.weein.bigdata.core.service.IBaseService;
import com.weein.bigdata.base.entity.ProductInfoDO;
/**
 *com.weein.bigdata.core.service.IProductInfoServices.java
 *2018-09-29 03:22:57
 * This was class generated by ant velocity
 */
public interface IProductInfoService extends IBaseService<ProductInfoDO,java.lang.String>{

}
