package com.weein.bigdata.core.service.impl;
import com.weein.bigdata.core.service.impl.BaseServiceImpl;
import com.weein.common.base.dao.IBaseMapper;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import com.weein.bigdata.dao.IBigdataGroupProductConfigurationMapper;
import com.weein.bigdata.core.service.IBigdataGroupProductConfigurationService;
import com.weein.bigdata.base.entity.BigdataGroupProductConfigurationDO;
/**
 *com.weein.bigdata.core.service.impl.IBigdataGroupProductConfigurationServices.java
 *2018-09-30 12:58:42
 * This was class generated by ant velocity
 */
@Service
public class BigdataGroupProductConfigurationServiceImpl extends BaseServiceImpl<BigdataGroupProductConfigurationDO,java.lang.String> implements IBigdataGroupProductConfigurationService{
	 
   @Resource
   private IBigdataGroupProductConfigurationMapper mapper;

   
   @Override
   protected IBaseMapper<BigdataGroupProductConfigurationDO,java.lang.String> getEntityMapper() {
	return mapper;
   }


   @Override
   public int deleteByGroupId(String groupId) {
	   return mapper.deleteByGroupId(groupId);
	   }
   
 
}
