package com.weein.bigdata.core.service.impl;
import com.weein.bigdata.core.service.impl.BaseServiceImpl;
import com.weein.common.base.dao.IBaseMapper;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import com.weein.bigdata.dao.ICouponInfoMapper;
import com.weein.bigdata.core.service.ICouponInfoService;
import com.weein.bigdata.base.entity.CouponInfoDO;
/**
 *com.weein.bigdata.core.service.impl.ICouponInfoServices.java
 *2018-08-29 01:27:31
 * This was class generated by ant velocity
 */
@Service
public class CouponInfoServiceImpl extends BaseServiceImpl<CouponInfoDO,java.lang.String> implements ICouponInfoService{
	 
   @Resource
   private ICouponInfoMapper mapper;

   
   @Override
   protected IBaseMapper<CouponInfoDO,java.lang.String> getEntityMapper() {
	return mapper;
   }
}
