package com.weein.bigdata.core.service.impl;
import com.weein.bigdata.core.service.impl.BaseServiceImpl;
import com.weein.common.base.dao.IBaseMapper;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import com.weein.bigdata.dao.IMobikeCityMapper;
import com.weein.bigdata.core.service.IMobikeCityService;
import com.weein.bigdata.base.entity.MobikeCityDO;
/**
 *com.weein.bigdata.core.service.impl.IMobikeCityServices.java
 *2018-09-27 05:18:25
 * This was class generated by ant velocity
 */
@Service
public class MobikeCityServiceImpl extends BaseServiceImpl<MobikeCityDO,java.lang.Integer> implements IMobikeCityService{
	 
   @Resource
   private IMobikeCityMapper mapper;

   
   @Override
   protected IBaseMapper<MobikeCityDO,java.lang.Integer> getEntityMapper() {
	return mapper;
   }
}
