package com.weein.bigdata.core.service.impl;
import com.weein.bigdata.core.service.impl.BaseServiceImpl;
import com.weein.common.base.dao.IBaseMapper;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import com.weein.bigdata.dao.IProductInfoMapper;
import com.weein.bigdata.core.service.IProductInfoService;
import com.weein.bigdata.base.entity.ProductInfoDO;
/**
 *com.weein.bigdata.core.service.impl.IProductInfoServices.java
 *2018-09-29 03:22:57
 * This was class generated by ant velocity
 */
@Service
public class ProductInfoServiceImpl extends BaseServiceImpl<ProductInfoDO,java.lang.String> implements IProductInfoService{
	 
   @Resource
   private IProductInfoMapper mapper;

   
   @Override
   protected IBaseMapper<ProductInfoDO,java.lang.String> getEntityMapper() {
	return mapper;
   }
}
